# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbb1286a845e3da539e13ef216c06ac604f29ac2aeddc9a1fbcb885281a2cc1904fc3f1a1874d12d4a8b42cecbe9fb98f01768333c8a7f836b2a3bbde305436

test:
  secret_key_base: 7e7ad322b9702ae85c0ffa095994b4c6e7fbcb3e60f881228a257afb54d2296bf90637f52368cf05065f49b7754d4cb7e564a5036856752a2df21c08469b51e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
